const express = require('express');
const cors = require('cors');
const authRoutes = require('./routes/auth.routes');
const mfaRoutes = require('./routes/mfa.routes'); 
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api/auth', authRoutes);
app.use('/api/mfa', mfaRoutes);
module.exports = app;